# Introduction

This repository aims to serve as a reference of materials to learn and
practice Python in the context of data science and/or machine learning.
The materials contained within this repository target a diverse audience
of Python users, including first-time Python users and those with
previous experience. If you are a first-time user, the curated resources
will contain information that will help you install Python and Jupyter
Notebook via Anaconda and begin familiarizing yourself with Python's
syntax and data structures. Students more familiar with Python may jump
into topic-specific resources as refreshers and references or even jump
directly into simulated use cases to practice their skills in an applied
scenario! Below are summaries of the two main arms of this repository:

## Use Cases

The `Use Cases` folder contains a number of sub-folders. Each sub-folder
contains a "Use Case", which can be thought of as an example assignment.
Assignments include a data set or multiple data sets to use in answering
questions contained in a `Student Assessment.MD` file in each folder.
These assignments outline specific competencies that they intend to
assess.

-   An assignment prompt (`Student Assessment.MD`): This markdown
    document will contain all relevant questions and information
    (outside of the CSV data files mentioned below) to "complete" a use
    case assignment. This document will include a brief introduction to
    the use case topic, relevant resources/references when appropriate,
    and tasks/questions to complete/answer for each use case.\
-   CSV data file(s): Data files relevant for completion of the
    assignment/use case\
-   A walkthrough Jupyter notebook "solution": A Jupyter notebook of
    **a** walkthrough solution to the student assessment prompts. As
    noted in each use case, this walkthrough notebook does not
    necessarily present a singular correct solution (or even necessarily
    the most concise\
-   An additional `Instructor Materials` subfolder: This folder is not
    relevant for the completion or understanding of any assessments, as
    it simply contains relevant figures/files presented in the
    `Student Assessment.MD` as well as a Jupyter Notebook simulating
    data for each use case (when applicable).\
-   An `R` folder, containing walkthrough RMD and HTML documents
    generated in R (using RMarkdown) that walk through steps paralleling
    the walkthrough Jupyter Notebooks. These files will not be fully
    introductory to R (assuming some base familiarity) but are
    instructive in assuming only a basic understanding of R before then
    walking through the student assessment "solutions".

*We would love to hear and implement additional, relevant use cases from instructors, statisticians, pharmacists, and other analytics professionals! If you have a relevant use case you would be comfortable sharing, please visit [following Google form](https://forms.gle/crQJqGNvyjGpJa9y7) and submit a brief proposal, describing your use case.*

## Resource Curation

**Chapter 3** of this book is solely a running list of relevant, Python resources. We hope that this list may serve as a quick reference for LinkedInLearning or YouTube lectures, written references, and/or other open-resource websites. These resources are additionally contained under the file `Resource Spreadsheet.MD`. This file organizes the resources as they pertain to different topics related to the Python for Data Management & Analytics course (although these topics certainly extend to building competencies in Python for data science outside of the course as well)! See the the list below for an aggregated (and growing) collection of resources:

