
# List of Curated Python & Statistical Education Resources 


#### Python Courses

-   Python Tutorial for Beginners
    ([Link](https://www.youtube.com/playlist?list=PLsyeobzWxl7poL9JTVyndKe62ieoN-MZ3))

-   Forbes Best Free online data science courses in 2019
    ([Link](https://www.forbes.com/sites/bernardmarr/2020/02/24/the-9-best-free-online-data-science-courses-in-2020/#669fdab32bbf))

-   Data Camp ([Link](https://www.datacamp.com/community/open-courses))
    (Python plus more)

-   Python Beginner Course - Breathe Code
    ([Link](https://www.youtube.com/playlist?list=PLCVs_S8Skwp8MzELbLAm-v9wbUS-toTkt))

-   Coursera - Python Genomic Data Science Specialization
    ([Link](https://www.coursera.org/learn/python-genomics))

-   Data Science Plus
    ([Link](https://datascienceplus.com/category/introduction/?tdo_tag=Python))

    -   Impressive review of Stats Methods (Linear regression)

-   "Data Professor" - Python search playlist
    [(Link](https://www.youtube.com/channel/UCV8e2g4IWQqK71bbzGDEI4Q/search?query=python))

-   Google Cloud Platform
    ([Link](https://www.youtube.com/user/googlecloudplatform/search?query=python))

-   Coursera

    -   Machine Learning with Python
        ([Link](https://www.coursera.org/learn/machine-learning-with-python))

    -   Data Analysis with Python
        ([Link](https://www.coursera.org/learn/data-analysis-with-python))

    -   Specializations

        -   Python for Everybody Specialization -
            ([Link](https://www.coursera.org/specializations/python))
        -   Applied Data Science with Python Specialization -
            ([Link](https://www.coursera.org/specializations/data-science-python))

-   Kaggle

    -   NR - good for introductory learners

#### General References/Resources:

-   <https://www.mastersindatascience.org/>
-   <https://pythonhealthcare.org/>
-   <https://datacarpentry.org/>
-   [Knowledge Tree](http://www.pitt.edu/~taler/KnowledgeTree.html) -
    Pitt

#### LinkedIn Learning:

-   *Resources pending, currently contained mostly in
    ResourceSpreadsheet.MD*

#### Others locations of information

-   OHSU - Wiki that reviews other resources - [Main
    page](https://www.clinfowiki.org/wiki/index.php/Main_Page), [Article
    list](https://www.clinfowiki.org/wiki/index.php/Category:HI5313-2015-FALL)

-   ICS Lab Tutors -
    [Link](http://tutors.ics.uci.edu/index.php/0-python-resources/85-python-resources)

    -   Python Exercises

-   "The Ultimate Data Science Prerequisite Learning List" -
    [Link](https://towardsdatascience.com/the-ultimate-data-science-prerequisite-learning-list-348ce89805f9)

    -   List of List

#### Statistics Materials:

-   UTHealth - Biostatistics for the Clinician -
    [Link](https://www.uth.tmc.edu/uth_orgs/educ_dev/oser/L1_TOC.HTM)

-   Youtube - Brandon Fultz -
    [Link](https://www.youtube.com/user/BCFoltz)

-   Youtube "Stats Quest" - Josh Starmer -
    [Link](https://www.youtube.com/channel/UCtYLUTtgS3k1Fg4y5tAhLbw)

-   BMJ Statistics -
    [Link](https://www.bmj.com/about-bmj/resources-readers/publications/statistics-square-one) \*
    Kenyon - Biology
    ([Link](http://biology.kenyon.edu/courses/biol09/stats.htm))

-   Health Knowledge UK, Public Health Textbook, statistical methods
    section
    ([Link](https://www.healthknowledge.org.uk/public-health-textbook/research-methods/1b-statistical-methods))

-   StatR Analysis - Which test to choose -
    ([Link](https://statranalysis.net/2015/07/27/choosing-the-correct-statistical-test/))

-   Medium, Towards Data Science - "Everything You Need To Know about
    Hypothesis Testing --- Part II"
    ([Link](https://towardsdatascience.com/everything-you-need-to-know-about-hypothesis-testing-part-ii-f0526be27b7d))

-   Concordia University - "OER Statistics"
    ([Link](https://libguides.cu-portland.edu/OER/statistics))

-   Open UMich Introduction to Statistics -
    [Link](https://open.umich.edu/find/open-educational-resources/statistics/statistics-250-introduction-statistics-data-analysis))

-   OER Hopkins "Introduction to Biostatistics" -
    ([Link](http://ocw.jhsph.edu/index.cfm/go/viewCourse/course/introbiostats/coursePage/index/))

#### Books

-   Clinical Data as the Basic Staple of Health Learning: Creating and
    Protecting a Public Good: Workshop Summary (HSLS)

-   Neural Data Science : A Primer with MATLAB® and Python (HSLS)

-   Python for Bioinformatics (HSLS)

-   Python for Everybody - trinket Open book -
    ([Link](https://books.trinket.io/pfe/))

    -   Very easy to read

#### Assessments/Homework

-   NHLBI Big Data Analysis Challenge -
    ([Link](https://www.nhlbi.nih.gov/grants-and-training/funding-opportunities-and-contacts/NHLBI-heart-failure-data-challenge))
-   Introduction to VA Pharmacy Data Sources -
    ([Link](https://www.hsrd.research.va.gov/for_researchers/cyber_seminars/archives/video_archive.cfm?SessionID=3543))

#### Data sets

-   <https://sleepdata.org/datasets>

-   <https://www.icpsr.umich.edu/web/pages/ICPSR/index.html>

-   <https://www.icpsr.umich.edu/web/instructors/biblio/resources>

-   Pediatric Intensive Care Data - ([Link](http://pic.nbscn.org/))

    -   Github example of prediction -
        ([Link](https://github.com/Healthink/PIC))

-   NYU - public data sets
    ([Link](https://www.nyu.edu/about/policies-guidelines-compliance/policies-and-guidelines/ucaihs-policy-on-publicly-available-and-de-identified-data.html))

-   Berkley -
    ([Link](https://guides.lib.berkeley.edu/publichealth/healthstatistics/rawdata))

-   Synthetic EMR Data Set - <http://www.emrbots.org/>

-   R Bots

-   Synthetic EMR Data Set - ([Synthethic
    Mass](https://synthea.mitre.org/))

#### Fun Reads/Videos

-   Bringing AI to the Underserved Billions -
    ([Link](https://www.ted.com/talks/dr_rahul_panicker_bringing_ai_to_the_underserved_billions)),
    Ted Talk 12 minutes

-   How to keep human bias out of AI -
    ([Link](https://www.ted.com/talks/kriti_sharma_how_to_keep_human_bias_out_of_ai)),
    Ted Talk 12 minutes

-   Rayid Ghani -

-   ONC Overview of HealthCare Data Analytics -
    ([Link](https://www.youtube.com/watch?v=8vQWWNhjffc)) 20 minutes

-   Data Science in Healthcare, PyData NYC 2018 -
    ([Link](https://www.youtube.com/watch?v=Z9JZjc489XA))

-   BD2K - Exploratory Data Analysis -
    ([Link](https://www.youtube.com/watch?v=5rTb6AkKhds)) 60 minutes\

-   University of Virginia, Exploratory Data Analysis" -
    ([Link](https://www.youtube.com/watch?v=zHcQPKP6NpM)) 20 minutes

-   HBR

    -   Articles tagged with "Data" -
        ([Link](https://hbr.org/topic/data))
    -   "Use This Framework to Predict the Success of Your Big Data
        Project -
        ([Link](https://hbr.org/2020/02/use-this-framework-to-predict-the-success-of-your-big-data-project))
    -   Building a data science team -
        ([Link](https://hbr.org/2018/10/managing-a-data-science-team))

-   Python for Industry Pharmaceuticals and Healthcare -
    ([Link](https://www.youtube.com/watch?v=doTMGOPK1Cw)) (4 minutes)

-   Python vs R vs SAS, Simplilearn -
    ([Link](https://www.youtube.com/watch?v=HAvjZiAwCZg)) (20 minutes)

#### Articles

-   A Machine Learning Approach for the Detection and Characterization
    of Illicit Drug Dealers on Instagram: Model Evaluation Study -
    ([Link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6598421/))

    -   Python for language analysis

-   A validation of machine learning-based risk scores in the
    prehospital setting -
    ([Link](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0226518))

-   CHIME: COVID-19 Hospital Impact Model for Epidemics -
    ([Link](https://codeforphilly.org/projects/chime))

-   Simulate Covid-19 in your area with Python --- beyond SIR models
    (towardsdatascience.com) -
    ([Link](https://towardsdatascience.com/model-the-covid-19-epidemic-in-detail-with-python-98f0d13f3a0e))

-   HBR "The Kinds of Data Scientist" -
    ([Link](https://hbr.org/2018/11/the-kinds-of-data-scientist))

-   "Acquiring and Using Electronic Health Record Data"
    (<https://rethinkingclinicaltrials.org/>) -
    ([Link](https://rethinkingclinicaltrials.org/resources/acquiring-and-using-electronic-health-record-data/))

-   A machine learning approach predicts future risk to suicidal
    ideation from social media data -
    ([Link](https://www.nature.com/articles/s41746-020-0287-6))

-   "A dataset quantifying polypharmacy in the United States" -
    ([Link](https://www.nature.com/articles/sdata2017167#MOESM187))
