# Introduction

This site contains didactic and applied materials to aid learn and practice Python, specifically for application in data science and machine learning. 
These  materials target audiences with varying levels of comfort with Python, including first-time Python users learning and applying new skills or those with
familiarity to practice and demonstrate their skills in relevant use-cases. Applied materials (including use cases and available data, either simulated or publicily hosted) 
are specifically tailored to business and/or clinical use-cases in pharmacy. 

. If you are a first-time user, the curated resources
will contain information that will help you install Python and Jupyter
Notebook via Anaconda and begin familiarizing yourself with Python's
syntax and data structures. Students more familiar with Python may jump
into topic-specific resources as refreshers and references or even jump
directly into simulated use cases to practice their skills in an applied
scenario! Below are summaries of the two main arms of this repository:

## Use Cases

For purposes of this site and its [underlying GitHub repository](https://github.com/domdisanto/python_oer), 
a *"use case"* is defined as some data set and related tasks that were devloped in collaboration with 
industry partners. The data in these use cases is most often simulated data, with the data simulation
specifically mirroring essential contents and structure to data seen in practice by our industry collaborators. 



*Use Cases* are briefly outlined and summarized in Chapter 4, and the subsections of Chapter 5 include the individual use cases.
Each use case will contain a data set and/or linked or discussed, publicily available data set, an assignment or series of 
tasks to accomplish using the data, and an example walkthrough document in both R and Python (via Jupyter Notebook) that discusses
an example "solution" to the proposed tasks. 

*N.B. Walkthrough notebooks do not necessarily contain singularly correct solutions (or even necessarily the most concise or efficient) but simply present* ***a*** *method of solving each use case's specific tasks*.



We would love to hear and implement additional, relevant use cases from instructors, statisticians, pharmacists, and other analytics professionals! If you have a relevant use case you would be comfortable sharing, please visit [following Google form](https://forms.gle/crQJqGNvyjGpJa9y7) and submit a brief proposal, describing your use case.

## Resource Curation

**Chapter 3** of this book is solely a running list of relevant, Python resources. We hope that this list may serve as a quick reference for LinkedInLearning or YouTube lectures, written references, and/or other open-resource websites. Resources are organized according to various topics related to the Python for Data Management & Analytics course (although these topics certainly extend to building competencies in Python for data science outside of the course as well)! 
